/**
 * @since 2019-09-22 05:29
 * @author vivaxy
 */
export const GAME_START = 'GAME_START';
export const GAME_PAUSE = 'GAME_PAUSE';
export const GAME_RESUME = 'GAME_RESUME';
export const GAME_OVER = 'GAME_OVER';
export const GAME_RESET = 'GAME_RESET';

export const GAME_STATE_CHANGE = 'GAME_STATE_CHANGE';

export const UPDATE_GRID = 'UPDATE_GRID';
export const TETROMINO_CREATE = 'TETROMINO_CREATE';
export const TETROMINO_MOVE = 'TETROMINO_MOVE';
export const TETROMINO_SETTLED = 'TETROMINO_SETTLED';
export const TETROMINO_LEFT = 'TETROMINO_LEFT';
export const TETROMINO_RIGHT = 'TETROMINO_RIGHT';
export const TETROMINO_ROTATE = 'TETROMINO_ROTATE';
export const TETROMINO_DOWN = 'TETROMINO_DOWN';

export const SCORE_UPDATE = 'SCORE_UPDATE';
export const SPEED_UPDATE = 'SPEED_UPDATE';

export const TICK = 'TICK';
export const RENDER_LAYERS_ADD = 'RENDER_LAYERS_ADD';
export const RENDER_LAYERS_REMOVE = 'RENDER_LAYERS_REMOVE';
